name = "kaiano-wcs-website"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[env.production.vars]
PUBLIC_API_URL = "https://api.kaianolevine.com"
PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAACXUS6RYhJCvPzZg"

[env.preview.vars]
PUBLIC_API_URL = "https://api.kaianolevine.com"
PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAACXUS6RYhJCvPzZg"
